# Generated by Django 4.2.4 on 2023-09-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_rename_content_post_task_alter_post_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='date_due',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Task',
            new_name='task',
        ),
    ]
