# Generated by Django 4.2.4 on 2023-09-14 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_rename_date_posted_post_date_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_due',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
